// export { default as imgExample } from './img_example.png';
export { default as imgChatgptBook } from './img_chatgptBook.png';
export { default as imgFunctionalBook } from './img_functionalBook.png';
export { default as imgJsDeepDiveBook } from './img_jsDeepDiveBook.png';
export { default as imgRefactoringBook } from './img_refactoringBook.png';
export { default as imgJavaBook } from './img_java.jpeg';
export { default as imgTypescriptBook } from './img_typescript.jpeg';
export { default as imgAgi } from './img_agi.png';
export { default as imgClean } from './img_clean.png';
export { default as imgCore } from './img_core.jpeg';
export { default as imgCs } from './img_cs.jpeg';
export { default as imgGenius } from './img_genius.png';
export { default as imgGoogle } from './img_google.png';
export { default as imgJava } from './img_java.jpeg';
export { default as imgSql } from './img_sql.jpeg';
export { default as imgSlam } from './img_slam.png';
